### ISSUE TITLE
Caddyfile support

### ISSUE THREAD

**Issue by mastercactapus** [mastercactapus/caddy2-proxyprotocol#1]
This issue is to track adding Caddyfile support.

Proposed format differs slightly from the Caddy 1.x version to simplify it's use

No options/use defaults:
```Caddyfile
proxy_protocol {
  timeout 5s
  allow 0.0.0.0/0 1.2.3.4/0
}
```

Set override default timeout or allow ranges:
```Caddyfile
proxy_protocol {
  timeout 0
  allow 0.0.0.0/0 1.2.3.4/0
}
```

**Comment by mholt** [comment]
Cool, subscribing to this issue; will also see what we can do within Caddy to make it possible to add listener wrappers from the Caddyfile.

Since the order of the wrappers is important, I wonder if we need to let the user be able to specify that...

**Comment by francislavoie** [comment]
FYI I was thinking about ways to make this work, and I wrote this proposal https://github.com/caddyserver/caddy/issues/3669#issuecomment-706820214

**Comment by francislavoie** [comment]
I finally got around to implementing it. https://github.com/caddyserver/caddy/pull/3836

@mastercactapus I can make a PR to add support to this plugin, unless you want to take a crack at it. All you need to do is add a `UnmarshalCaddyfile` function (`caddyfile.Unmarshaler` interface) which parses the options.

Basically make sure there's no `d.NextArg()` and then loop over `d.NextBlock(0)` consuming each line of options in a switch statement.

Caddyfile will look something like this:

```
{
	servers {
		listener_wrappers {
			proxy_protocol {
				timeout 0
				allow 0.0.0.0/0 1.2.3.4/0
			}
			tls
		}
	}
}

foo.com {
}
```

**Comment by crysper** [comment]
Bumping this up!
