### ISSUE TITLE
TLS scene support

### ISSUE THREAD

**Issue by lxhao61** [mastercactapus/caddy2-proxyprotocol#2]
Hope to support the use of TLS scenarios. It is a real ‘proxy protocol’ protocol.

**Comment by mastercactapus** [comment]
I'm not sure I understand; PROXY is negotiated/sent before the TLS handshake or any other data is sent. It is protocol agnostic and should support anything later in the chain.

This plugin only implements support for the PROXY protocol specifically, versions 1 and 2, and must be loaded before the TLS handler:
https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

**Comment by lxhao61** [comment]
Sorry, I made a mistake. I thought that TLS scenes are not supported. The original TLS scenes can be enabled with {"wrapper":"tls"}.
